i18n/ja.toml
I don't think it is a perfect Japanese translation. However I think it can be usable.
=> added i18n/ja.toml as initial Japanese translation

docs/i18n.md, i18n/pt.toml
=> Add portuguese translation

data/it.toml, i18n/it.toml
Hi, I'm providing a possible italian translation for the weekdays/months and for the i18n.
Cheers
=> Italian translation

data/fr.toml, i18n/fr.toml, layouts/_default/single.html, layouts/_default/summary.html
This PR includes date management in French and a correction in FR i18n file.  
Thanks for your theme
=> Enhance French translation

docs/params-configurations.md, exampleSite/config.toml, layouts/_default/single.html
I have also added entries in the doc,
sorry about closing the last pr, I forgot to remove my own branding which I made for my website.
=> Added Valine language support.

docs/i18n.md, i18n/tr.toml
I added turkish translations and updated the i18n document
=> Add TR locale

docs/pages/CHANGELOG.md, docs/pages/params-configurations.mdx, hugo.example.toml, layouts/_default/single.html, src/input.css, src/js/main.js, static/css/output.css, static/js/main.js
Close #289
Note: The table of contents is not displayed on screens smaller than 1024 pixels. I need to think a little further about how to present it on a small-sized screen.
=> feat: support TOC in v3

i18n/ja.toml
This pull request makes minor adjustments to the Japanese translation in `i18n/ja.toml`. The changes include:
- Revised several phrases for a more natural flow
- Completed translations for previously untranslated words
These updates aim to enhance clarity and improve the overall user experience for Japanese-speaking users. Please review the changes for accuracy and naturalness. Thank you!
=> Enhance and Complete Japanese Translations

layouts/partials/head.html
Close #304.
For more information, please refer to the related issue.
=> refactor: supplement meta tags for SEO

docs/pages/post-page.md, docs/pages/post-page.mdx, layouts/_default/_markup/render-codeblock-mermaid.html, layouts/_default/baseof.html
=> feat: add mermaid support

i18n/fr.toml, i18n/pt.toml, i18n/zh.toml
=> fix: supplement translations in fr/pt

assets/js/grid.js, assets/js/main.js, layouts/_default/baseof.html, layouts/partials/back.html, layouts/partials/disqus.html, layouts/partials/footer.html, package.json, src/js/grid.js
=> fix: append footer on about page

layouts/partials/nav.html
Ref: https://github.com/saadeghi/daisyui/issues/116
Close #325
=> fix: add tabindex to dropdown content

assets/css/output.css, docs/pages/CHANGELOG.md, layouts/_default/single.html, layouts/partials/nav.html, src/input.css
=> feat: make TOC scrollable

docs/pages/CHANGELOG.md, docs/pages/params-configurations.mdx, hugo.example.toml, layouts/_default/single.html
=> feat: make images zoomable in the single post page

README.md, docs/pages/index.mdx, hugo.example.toml
=> docs: how to install

assets/css/output.css, docs/pages/CHANGELOG.md, docs/pages/post-page.mdx, layouts/_default/single.html, layouts/_default/summary.html
=> feat: whether to remove author display

docs/pages/CHANGELOG.md, layouts/_default/summary.html, layouts/partials/head.html, layouts/section/search.html
=> chore: prioritize page descriptions

layouts/section/posts.html
=> Should use title for posts then fallback to "archives"

assets/css/output.css, assets/js/grid.js, docs/pages/CHANGELOG.md, layouts/_default/term.html, layouts/_default/terms.html, layouts/index.html, src/js/grid.js
Refs: https://github.com/g1eny0ung/hugo-theme-dream/issues/352#issuecomment-2668970943, https://github.com/desandro/masonry/issues/906
=> perf: optimize layout shifts

docs/pages/CHANGELOG.md, layouts/_default/_markup/render-codeblock-mermaid.html
=> fix: escape mermaid before safe

decapCMS/index.html, layouts/_default/baseof.html, layouts/partials/commentSystemHeads.html, layouts/partials/commentSystems.html
=> fix: deprecate unpkg cdn

assets/js/toc.js, src/js/toc.js
=> fix: offset calculation
